modLoader = "javafml"
loaderVersion = "*"
license = "MIT"

[[mods]]
modId = "reeses_sodium_options"

version = "${version}"
displayName = "Reese's Sodium Options"

logoFile = "icon.png" #optional

authors = "FlashyReese"

description = '''
Replaces Sodium's Options Screen
'''

[[dependencies.reeses_sodium_options]]
modId = "minecraft"
type = "required"
versionRange = "[1.20.4,1.21.1)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.reeses_sodium_options]]
modId = "sodium"
type = "required"
versionRange = "[0.6.0-beta.1,0.6.0)"
ordering = "NONE"
side = "CLIENT"

[[mixins]]
config = "reeses-sodium-options.mixins.json"